---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
rvm:
  - 2.3.8
env:
  global:
    - PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      dist: trusty
      script:
      - bundle exec rake 'litmus:provision_list[travis_deb]'
      - bundle exec bolt command run 'apt-get install wget -y' -i inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec bolt command run 'puppet module install puppetlabs-postgresql' -n all -i inventory.yaml
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      dist: trusty
      script:
      - bundle exec rake 'litmus:provision_list[travis_deb]'
      - bundle exec bolt command run 'apt-get install wget -y' -i inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec bolt command run 'puppet module install puppetlabs-postgresql' -n all -i inventory.yaml
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      dist: trusty
      script:
      - bundle exec rake 'litmus:provision_list[travis_el]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec bolt command run 'puppet module install puppetlabs-postgresql' -n all -i inventory.yaml
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      dist: trusty
      script:
      - bundle exec rake 'litmus:provision_list[travis_el]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec bolt command run 'puppet module install puppetlabs-postgresql' -n all -i inventory.yaml
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file"
